services:
  todo:
    build: .
    image: ghcr.io/anujctrl/braindump:latest
    container_name: braindump
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - BRAINDUMP_HOME=/data
      - BRAINDUMP_DOCKER=1

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - DOCKER_API_VERSION=1.40
    command: braindump
